# Generated by Django 5.0.1 on 2024-03-18 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carné de identidad')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('apellidos', models.CharField(blank=True, max_length=30, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['nombre'],
            },
        ),
    ]
