# Generated by Django 5.0.1 on 2024-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=50, verbose_name='Autor del Post'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
