# Generated by Django 5.0.1 on 2024-03-21 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0004_alter_post_options_remove_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
